# Passive Mobs
kill @e[type=bat]
kill @e[type=pufferfish]
kill @e[type=rabbit]
kill @e[type=skeleton_horse]
kill @e[type=strider]

# Neutral Mobs
kill @e[type=cave_spider]
kill @e[type=drowned]
kill @e[type=enderman]
kill @e[type=piglin]
kill @e[type=spider]
kill @e[type=trader_llama]
kill @e[type=zombified_piglin]

# Hostile Mobs
kill @e[type=blaze]
kill @e[type=bogged]
kill @e[type=breeze]
kill @e[type=creaking]
kill @e[type=creeper]
kill @e[type=elder_guardian]
kill @e[type=endermite]
kill @e[type=evoker]
kill @e[type=ghast]
kill @e[type=guardian]
kill @e[type=hoglin]
kill @e[type=husk]
kill @e[type=magma_cube]
kill @e[type=phantom]
kill @e[type=piglin_brute]
kill @e[type=pillager]
kill @e[type=ravager]
kill @e[type=shulker]
kill @e[type=silverfish]
kill @e[type=skeleton]
kill @e[type=slime]
kill @e[type=stray]
kill @e[type=vex]
kill @e[type=vindicator]
kill @e[type=warden]
kill @e[type=witch]
kill @e[type=wither_skeleton]
kill @e[type=zoglin]
kill @e[type=zombie]
kill @e[type=zombie_villager]

# Unused Mobs
kill @e[type=giant]
kill @e[type=illusioner]
kill @e[type=zombie_horse]

# Misc
kill @e[type=arrow]
kill @e[type=trident]
